# Generated by Django 2.1 on 2018-09-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_url', models.URLField()),
                ('Video_title', models.CharField(max_length=200)),
                ('Video_text', models.TextField()),
                ('Video_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
