# Generated by Django 2.1 on 2018-09-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shufic', '0003_auto_20180914_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='Video_date',
        ),
    ]
