# Generated by Django 2.1 on 2018-09-14 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shufic', '0004_remove_video_video_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Video_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
