# Generated by Django 2.1 on 2018-09-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shufic', '0005_video_video_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_text', models.TextField()),
                ('Comment_Video', models.ForeignKey(on_delete=True, to='shufic.Video')),
            ],
        ),
    ]
